version: 2

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=1

builds:
  - id: tetrigo-darwin-amd64
    binary: tetrigo
    main: ./cmd/tetrigo
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath

  - id: tetrigo-darwin-arm64
    binary: tetrigo
    main: ./cmd/tetrigo
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath

  - id: tetrigo-linux-amd64
    binary: tetrigo
    main: ./cmd/tetrigo
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath

  - id: tetrigo-linux-arm64
    binary: tetrigo
    main: ./cmd/tetrigo
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath

  - id: tetrigo-windows-amd64
    binary: tetrigo
    main: ./cmd/tetrigo
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe

  - id: tetrigo-windows-arm64
    binary: tetrigo
    main: ./cmd/tetrigo
    goarch:
      - arm64
    goos:
      - windows
    env:
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe

universal_binaries:
  - id: tetrigo-darwin-universal
    ids:
      - tetrigo-darwin-amd64
      - tetrigo-darwin-arm64
    replace: true
    name_template: "tetrigo"

archives:
  - name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE.txt
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
