version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - binary: tetrigo
    main: ./cmd/tetrigo
    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE.txt
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
