version: '3'

tasks:
  build:
    cmds:
      - go build -v -o ./bin/ {{.CLI_ARGS}} ./...
  test:
    cmds:
      - go test -cover {{.CLI_ARGS}} ./...
  run:
    cmds:
      - go run . {{.CLI_ARGS}}
  cover:
    cmds:
      - go test -coverprofile=cover.out {{.CLI_ARGS}} ./...
      - go tool cover -html=cover.out