Output ./docs/assets/readme-demo.gif

Set FontSize 16
Set Width 600
Set Height 600
Set PlaybackSpeed 1
Set TypingSpeed 1ms

Hide
Type "go build -o ./ ./..."
Enter
Type "clear"
Enter
Set TypingSpeed 100ms
Show

Type "./tetrigo"
Enter

Sleep 2s

# menu
Down
Enter

# game
Sleep 1s
Type@1s "lli"

Sleep 2s
Space

Sleep 2s
Type@1s "jjji"

Sleep 2s
Type@1s "juji"

Sleep 2s
Escape
Sleep 2s

Hide
Set TypingSpeed 1ms
Escape
Type "rm ./tetrigo"
Enter